### ISSUE TITLE
Fehler nach Deinstallation

### ISSUE THREAD

**Issue by MarkSau** [ioBroker/ioBroker.whatsapp-cmb#5]
Ich habe den Adapter testweise mal installiert und probiert, rein aus Interesse. Eigentlich habe ich Telegram und Pushover im Einsatz. Wollte mal sehn was ich mit Whatsapp so machen kann. Resüme: ich brauche den nicht wirklich.
Also fix wieder deinstalliert über "adapter löschen".
Dann kommen vom Javascript Adapter ganz viele Fehlermeldungen, was vermuten lässt dass das Löschen noch Reste hinterlässt.
Ich habe den Whatsapp Adapter also wieder installiert, damit die Fehlermeldungen wegbleiben.
Einen Lösungsansatz wäre hier sehr hilfreich..
Danke
`2020-09-22 15:31:18.570 - warn: readDir will not read this directory () in future versions: whatsapp-cmb is not an object of type "meta"
2020-09-22 15:31:19.588 - error: host.MSNUC-IOB Cannot write files: /opt/iobroker/iobroker-data/files/whatsapp-cmb.admin/_data.json: ENOENT: no such file or directory, open '/opt/iobroker/iobroker-data/files/whatsapp-cmb.admin/_data.json'
2020-09-22 15:31:40.039 - warn: javascript.0 (27814) getState "system.adapter.whatsapp-cmb.0.uptime" not found (3)
2020-09-22 15:31:40.055 - warn: javascript.0 (27814) at script.js.common.VIS.06_iobroker_adapter_html_sp5:135:24
2020-09-22 15:31:40.056 - warn: javascript.0 (27814) at Object.result.each (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:785:29)
2020-09-22 15:31:40.057 - warn: javascript.0 (27814) at writeHTML (script.js.common.VIS.06_iobroker_adapter_html_sp5:130:29)
2020-09-22 15:31:40.057 - warn: javascript.0 (27814) at Object. (script.js.common.VIS.06_iobroker_adapter_html_sp5:160:2)
2020-09-22 15:31:40.058 - warn: javascript.0 (27814) at Job.job (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1273:34)
2020-09-22 15:31:40.058 - warn: javascript.0 (27814) at Job.invoke (/opt/iobroker/node_modules/node-schedule/lib/schedule.js:173:10)
2020-09-22 15:31:40.058 - warn: javascript.0 (27814) at /opt/iobroker/node_modules/node-schedule/lib/schedule.js:552:11
2020-09-22 15:31:40.059 - warn: javascript.0 (27814) at Timeout._onTimeout (/opt/iobroker/node_modules/node-schedule/lib/schedule.js:510:7)
2020-09-22 15:31:40.059 - warn: javascript.0 (27814) at listOnTimeout (internal/timers.js:554:17)
2020-09-22 15:31:40.060 - warn: javascript.0 (27814) at processTimers (internal/timers.js:497:7)
2020-09-22 15:31:40.060 - warn: javascript.0 (27814) getState "system.adapter.whatsapp-cmb.0.memHeapUsed" not found (3)
2020-09-22 15:31:40.062 - warn: javascript.0 (27814) at script.js.common.VIS.06_iobroker_adapter_html_sp5:136:16
2020-09-22 15:31:40.062 - warn: javascript.0 (27814) at Object.result.each (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:785:29)
2020-09-22 15:31:40.063 - warn: javascript.0 (27814) at writeHTML (script.js.common.VIS.06_iobroker_adapter_html_sp5:130:29)
2020-09-22 15:31:40.063 - warn: javascript.0 (27814) at Object. (script.js.common.VIS.06_iobroker_adapter_html_sp5:160:2)
2020-09-22 15:31:40.063 - warn: javascript.0 (27814) at Job.job (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1273:34)
2020-09-22 15:31:40.064 - warn: javascript.0 (27814) at Job.invoke (/opt/iobroker/node_modules/node-schedule/lib/schedule.js:173:10)
2020-09-22 15:31:40.064 - warn: javascript.0 (27814) at /opt/iobroker/node_modules/node-schedule/lib/schedule.js:552:11
2020-09-22 15:31:40.064 - warn: javascript.0 (27814) at Timeout._onTimeout (/opt/iobroker/node_modules/node-schedule/lib/schedule.js:510:7)
2020-09-22 15:31:40.064 - warn: javascript.0 (27814) at listOnTimeout (internal/timers.js:554:17)
2020-09-22 15:31:40.065 - warn: javascript.0 (27814) at processTimers (internal/timers.js:497:7)
2020-09-22 15:31:40.065 - warn: javascript.0 (27814) getState "system.adapter.whatsapp-cmb.0.memHeapTotal" not found (3)
2020-09-22 15:31:40.067 - warn: javascript.0 (27814) at script.js.common.VIS.06_iobroker_adapter_html_sp5:137:16
2020-09-22 15:31:40.067 - warn: javascript.0 (27814) at Object.result.each (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:785:29)
2020-09-22 15:31:40.068 - warn: javascript.0 (27814) at writeHTML (script.js.common.VIS.06_iobroker_adapter_html_sp5:130:29)
2020-09-22 15:31:40.068 - warn: javascript.0 (27814) at Object. (script.js.common.VIS.06_iobroker_adapter_html_sp5:160:2)
2020-09-22 15:31:40.069 - warn: javascript.0 (27814) at Job.job (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1273:34)
2020-09-22 15:31:40.069 - warn: javascript.0 (27814) at Job.invoke (/opt/iobroker/node_modules/node-schedule/lib/schedule.js:173:10)
2020-09-22 15:31:40.069 - warn: javascript.0 (27814) at /opt/iobroker/node_modules/node-schedule/lib/schedule.js:552:11
2020-09-22 15:31:40.070 - warn: javascript.0 (27814) at Timeout._onTimeout (/opt/iobroker/node_modules/node-schedule/lib/schedule.js:510:7)
2020-09-22 15:31:40.070 - warn: javascript.0 (27814) at listOnTimeout (internal/timers.js:554:17)
2020-09-22 15:31:40.071 - warn: javascript.0 (27814) at processTimers (internal/timers.js:497:7)
2020-09-22 15:32:00.038 - warn: javascript.0 (27814) getState "system.adapter.whatsapp-cmb.0.uptime" not found (3)
2020-09-22 15:32:00.040 - warn: javascript.0 (27814) at script.js.common.VIS.06_iobroker_adapter_html_sp5:135:24
2020-09-22 15:32:00.040 - warn: javascript.0 (27814) at Object.result.each (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:785:29)
2020-09-22 15:32:00.041 - warn: javascript.0 (27814) at writeHTML (script.js.common.VIS.06_iobroker_adapter_html_sp5:130:29)
2020-09-22 15:32:00.041 - warn: javascript.0 (27814) at Object. (script.js.common.VIS.06_iobroker_adapter_html_sp5:160:2)
2020-09-22 15:32:00.041 - warn: javascript.0 (27814) at Job.job (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1273:34)
2020-09-22 15:32:00.041 - warn: javascript.0 (27814) at Job.invoke (/opt/iobroker/node_modules/node-schedule/lib/schedule.js:173:10)
2020-09-22 15:32:00.041 - warn: javascript.0 (27814) at /opt/iobroker/node_modules/node-schedule/lib/schedule.js:552:11
2020-09-22 15:32:00.041 - warn: javascript.0 (27814) at Timeout._onTimeout (/opt/iobroker/node_modules/node-schedule/lib/schedule.js:510:7)
2020-09-22 15:32:00.042 - warn: javascript.0 (27814) at listOnTimeout (internal/timers.js:554:17)
2020-09-22 15:32:00.042 - warn: javascript.0 (27814) at processTimers (internal/timers.js:497:7)
2020-09-22 15:32:00.042 - warn: javascript.0 (27814) getState "system.adapter.whatsapp-cmb.0.memHeapUsed" not found (3)
2020-09-22 15:32:00.043 - warn: javascript.0 (27814) at script.js.common.VIS.06_iobroker_adapter_html_sp5:136:16
2020-09-22 15:32:00.044 - warn: javascript.0 (27814) at Object.result.each (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:785:29)
2020-09-22 15:32:00.044 - warn: javascript.0 (27814) at writeHTML (script.js.common.VIS.06_iobroker_adapter_html_sp5:130:29)
2020-09-22 15:32:00.044 - warn: javascript.0 (27814) at Object. (script.js.common.VIS.06_iobroker_adapter_html_sp5:160:2)
2020-09-22 15:32:00.044 - warn: javascript.0 (27814) at Job.job (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1273:34)
2020-09-22 15:32:00.044 - warn: javascript.0 (27814) at Job.invoke (/opt/iobroker/node_modules/node-schedule/lib/schedule.js:173:10)
2020-09-22 15:32:00.044 - warn: javascript.0 (27814) at /opt/iobroker/node_modules/node-schedule/lib/schedule.js:552:11
2020-09-22 15:32:00.045 - warn: javascript.0 (27814) at Timeout._onTimeout (/opt/iobroker/node_modules/node-schedule/lib/schedule.js:510:7)
2020-09-22 15:32:00.045 - warn: javascript.0 (27814) at listOnTimeout (internal/timers.js:554:17)
2020-09-22 15:32:00.045 - warn: javascript.0 (27814) at processTimers (internal/timers.js:497:7)
2020-09-22 15:32:00.045 - warn: javascript.0 (27814) getState "system.adapter.whatsapp-cmb.0.memHeapTotal" not found (3)
2020-09-22 15:32:00.046 - warn: javascript.0 (27814) at script.js.common.VIS.06_iobroker_adapter_html_sp5:137:16
2020-09-22 15:32:00.047 - warn: javascript.0 (27814) at Object.result.each (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:785:29)
2020-09-22 15:32:00.047 - warn: javascript.0 (27814) at writeHTML (script.js.common.VIS.06_iobroker_adapter_html_sp5:130:29)
2020-09-22 15:32:00.047 - warn: javascript.0 (27814) at Object. (script.js.common.VIS.06_iobroker_adapter_html_sp5:160:2)
2020-09-22 15:32:00.047 - warn: javascript.0 (27814) at Job.job (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1273:34)
2020-09-22 15:32:00.047 - warn: javascript.0 (27814) at Job.invoke (/opt/iobroker/node_modules/node-schedule/lib/schedule.js:173:10)
2020-09-22 15:32:00.048 - warn: javascript.0 (27814) at /opt/iobroker/node_modules/node-schedule/lib/schedule.js:552:11
2020-09-22 15:32:00.048 - warn: javascript.0 (27814) at Timeout._onTimeout (/opt/iobroker/node_modules/node-schedule/lib/schedule.js:510:7)
2020-09-22 15:32:00.048 - warn: javascript.0 (27814) at listOnTimeout (internal/timers.js:554:17)
2020-09-22 15:32:00.048 - warn: javascript.0 (27814) at processTimers (internal/timers.js:497:7)
2020-09-22 15:32:20.035 - warn: javascript.0 (27814) getState "system.adapter.whatsapp-cmb.0.uptime" not found (3)
2020-09-22 15:32:20.037 - warn: javascript.0 (27814) at script.js.common.VIS.06_iobroker_adapter_html_sp5:135:24
2020-09-22 15:32:20.038 - warn: javascript.0 (27814) at Object.result.each (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:785:29)
2020-09-22 15:32:20.038 - warn: javascript.0 (27814) at writeHTML (script.js.common.VIS.06_iobroker_adapter_html_sp5:130:29)
2020-09-22 15:32:20.038 - warn: javascript.0 (27814) at Object. (script.js.common.VIS.06_iobroker_adapter_html_sp5:160:2)
2020-09-22 15:32:20.038 - warn: javascript.0 (27814) at Job.job (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1273:34)
2020-09-22 15:32:20.039 - warn: javascript.0 (27814) at Job.invoke (/opt/iobroker/node_modules/node-schedule/lib/schedule.js:173:10)
2020-09-22 15:32:20.039 - warn: javascript.0 (27814) at /opt/iobroker/node_modules/node-schedule/lib/schedule.js:552:11
2020-09-22 15:32:20.039 - warn: javascript.0 (27814) at Timeout._onTimeout (/opt/iobroker/node_modules/node-schedule/lib/schedule.js:510:7)
2020-09-22 15:32:20.039 - warn: javascript.0 (27814) at listOnTimeout (internal/timers.js:554:17)
2020-09-22 15:32:20.039 - warn: javascript.0 (27814) at processTimers (internal/timers.js:497:7)
2020-09-22 15:32:20.039 - warn: javascript.0 (27814) getState "system.adapter.whatsapp-cmb.0.memHeapUsed" not found (3)
2020-09-22 15:32:20.041 - warn: javascript.0 (27814) at script.js.common.VIS.06_iobroker_adapter_html_sp5:136:16
2020-09-22 15:32:20.041 - warn: javascript.0 (27814) at Object.result.each (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:785:29)
2020-09-22 15:32:20.041 - warn: javascript.0 (27814) at writeHTML (script.js.common.VIS.06_iobroker_adapter_html_sp5:130:29)
2020-09-22 15:32:20.042 - warn: javascript.0 (27814) at Object. (script.js.common.VIS.06_iobroker_adapter_html_sp5:160:2)
2020-09-22 15:32:20.042 - warn: javascript.0 (27814) at Job.job (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1273:34)
2020-09-22 15:32:20.042 - warn: javascript.0 (27814) at Job.invoke (/opt/iobroker/node_modules/node-schedule/lib/schedule.js:173:10)
2020-09-22 15:32:20.042 - warn: javascript.0 (27814) at /opt/iobroker/node_modules/node-schedule/lib/schedule.js:552:11
2020-09-22 15:32:20.043 - warn: javascript.0 (27814) at Timeout._onTimeout (/opt/iobroker/node_modules/node-schedule/lib/schedule.js:510:7)
2020-09-22 15:32:20.043 - warn: javascript.0 (27814) at listOnTimeout (internal/timers.js:554:17)
2020-09-22 15:32:20.043 - warn: javascript.0 (27814) at processTimers (internal/timers.js:497:7)
2020-09-22 15:32:20.043 - warn: javascript.0 (27814) getState "system.adapter.whatsapp-cmb.0.memHeapTotal" not found (3)
2020-09-22 15:32:20.045 - warn: javascript.0 (27814) at script.js.common.VIS.06_iobroker_adapter_html_sp5:137:16
2020-09-22 15:32:20.045 - warn: javascript.0 (27814) at Object.result.each (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:785:29)
2020-09-22 15:32:20.045 - warn: javascript.0 (27814) at writeHTML (script.js.common.VIS.06_iobroker_adapter_html_sp5:130:29)
2020-09-22 15:32:20.046 - warn: javascript.0 (27814) at Object. (script.js.common.VIS.06_iobroker_adapter_html_sp5:160:2)
2020-09-22 15:32:20.046 - warn: javascript.0 (27814) at Job.job (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1273:34)
2020-09-22 15:32:20.046 - warn: javascript.0 (27814) at Job.invoke (/opt/iobroker/node_modules/node-schedule/lib/schedule.js:173:10)
2020-09-22 15:32:20.046 - warn: javascript.0 (27814) at /opt/iobroker/node_modules/node-schedule/lib/schedule.js:552:11
2020-09-22 15:32:20.046 - warn: javascript.0 (27814) at Timeout._onTimeout (/opt/iobroker/node_modules/node-schedule/lib/schedule.js:510:7)
2020-09-22 15:32:20.047 - warn: javascript.0 (27814) at listOnTimeout (internal/timers.js:554:17)
2020-09-22 15:32:20.047 - warn: javascript.0 (27814) at processTimers (internal/timers.js:497:7)
2020-09-22 15:32:40.050 - warn: javascript.0 (27814) getState "system.adapter.whatsapp-cmb.0.uptime" not found (3)
2020-09-22 15:32:40.052 - warn: javascript.0 (27814) at script.js.common.VIS.06_iobroker_adapter_html_sp5:135:24
2020-09-22 15:32:40.052 - warn: javascript.0 (27814) at Object.result.each (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:785:29)
2020-09-22 15:32:40.052 - warn: javascript.0 (27814) at writeHTML (script.js.common.VIS.06_iobroker_adapter_html_sp5:130:29)
2020-09-22 15:32:40.053 - warn: javascript.0 (27814) at Object. (script.js.common.VIS.06_iobroker_adapter_html_sp5:160:2)
2020-09-22 15:32:40.053 - warn: javascript.0 (27814) at Job.job (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1273:34)
2020-09-22 15:32:40.053 - warn: javascript.0 (27814) at Job.invoke (/opt/iobroker/node_modules/node-schedule/lib/schedule.js:173:10)
2020-09-22 15:32:40.053 - warn: javascript.0 (27814) at /opt/iobroker/node_modules/node-schedule/lib/schedule.js:552:11
2020-09-22 15:32:40.053 - warn: javascript.0 (27814) at Timeout._onTimeout (/opt/iobroker/node_modules/node-schedule/lib/schedule.js:510:7)
2020-09-22 15:32:40.053 - warn: javascript.0 (27814) at listOnTimeout (internal/timers.js:554:17)
2020-09-22 15:32:40.053 - warn: javascript.0 (27814) at processTimers (internal/timers.js:497:7)
2020-09-22 15:32:40.054 - warn: javascript.0 (27814) getState "system.adapter.whatsapp-cmb.0.memHeapUsed" not found (3)
2020-09-22 15:32:40.055 - warn: javascript.0 (27814) at script.js.common.VIS.06_iobroker_adapter_html_sp5:136:16
2020-09-22 15:32:40.055 - warn: javascript.0 (27814) at Object.result.each (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:785:29)
2020-09-22 15:32:40.056 - warn: javascript.0 (27814) at writeHTML (script.js.common.VIS.06_iobroker_adapter_html_sp5:130:29)
2020-09-22 15:32:40.056 - warn: javascript.0 (27814) at Object. (script.js.common.VIS.06_iobroker_adapter_html_sp5:160:2)
2020-09-22 15:32:40.056 - warn: javascript.0 (27814) at Job.job (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1273:34)
2020-09-22 15:32:40.056 - warn: javascript.0 (27814) at Job.invoke (/opt/iobroker/node_modules/node-schedule/lib/schedule.js:173:10)
2020-09-22 15:32:40.056 - warn: javascript.0 (27814) at /opt/iobroker/node_modules/node-schedule/lib/schedule.js:552:11
2020-09-22 15:32:40.057 - warn: javascript.0 (27814) at Timeout._onTimeout (/opt/iobroker/node_modules/node-schedule/lib/schedule.js:510:7)
2020-09-22 15:32:40.057 - warn: javascript.0 (27814) at listOnTimeout (internal/timers.js:554:17)
2020-09-22 15:32:40.057 - warn: javascript.0 (27814) at processTimers (internal/timers.js:497:7)
2020-09-22 15:32:40.057 - warn: javascript.0 (27814) getState "system.adapter.whatsapp-cmb.0.memHeapTotal" not found (3)
2020-09-22 15:32:40.059 - warn: javascript.0 (27814) at script.js.common.VIS.06_iobroker_adapter_html_sp5:137:16
2020-09-22 15:32:40.060 - warn: javascript.0 (27814) at Object.result.each (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:785:29)
2020-09-22 15:32:40.060 - warn: javascript.0 (27814) at writeHTML (script.js.common.VIS.06_iobroker_adapter_html_sp5:130:29)
2020-09-22 15:32:40.060 - warn: javascript.0 (27814) at Object. (script.js.common.VIS.06_iobroker_adapter_html_sp5:160:2)
2020-09-22 15:32:40.060 - warn: javascript.0 (27814) at Job.job (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1273:34)
2020-09-22 15:32:40.060 - warn: javascript.0 (27814) at Job.invoke (/opt/iobroker/node_modules/node-schedule/lib/schedule.js:173:10)
2020-09-22 15:32:40.060 - warn: javascript.0 (27814) at /opt/iobroker/node_modules/node-schedule/lib/schedule.js:552:11
2020-09-22 15:32:40.061 - warn: javascript.0 (27814) at Timeout._onTimeout (/opt/iobroker/node_modules/node-schedule/lib/schedule.js:510:7)
2020-09-22 15:32:40.061 - warn: javascript.0 (27814) at listOnTimeout (internal/timers.js:554:17)
2020-09-22 15:32:40.061 - warn: javascript.0 (27814) at processTimers (internal/timers.js:497:7)`

`

**Comment by MarkSau** [comment]
ok...habe jetzt mal die Instanz zuerst und dann den Adapter gelöscht...
Nun kommen die Fehler nicht mehr...

**Comment by MarkSau** [comment]
Update: Ich habe nun zuerst die Instanz und dann erst den Adapter deinstalliert.
Nun kommen keine derartigen Fehler mehr.

**Comment by GermanBluefox** [comment]
Welche version von js-controller ist das?

**Comment by kxn25** [comment]
Noch ein Hinweis:
Bei der Deinstallation darf in keinem Skript ein Block von dem Adapter sein, sonnst kann Blockly nicht mehr geöffnet werden.
